### ISSUE TITLE
Media queries support?

### ISSUE THREAD

**Issue by pukhalski** [sabeurthabti/react-native-css#1]
I assume it should work since the module simply creates a json structure. Just asking to be sure that it works.

**Comment by sabeurthabti** [comment]
Not sure if React-native css supports media queries. I might make this to be compatible with React. Please note, this module isn't fully complete. @pukhalski

**Comment by punkwang** [comment]
![snip20150422_3](https://cloud.githubusercontent.com/assets/5732547/7280847/2021b61c-e958-11e4-9cc3-ffb7dff3d3e7.png)
![snip20150422_4](https://cloud.githubusercontent.com/assets/5732547/7280846/1fca7bf4-e958-11e4-948d-a57cfef778c1.png)

**Comment by sabeurthabti** [comment]
@pukhalski  yep I noticed that error. 

https://github.com/facebook/react-native/issues/971, checking if react-native has support for FS.  I will work on it tonight.

**Comment by sabeurthabti** [comment]
@pukhalski 
I will update the doc soon. 

I think React-native doesn't have support for node modules. So i found this alternative:

1. please update to version 1.1.1 of this project: `npm install react-native-css@1.1.1 --save`
2. make a `style.css` within your project
3.  add the follow to your package.json scripts json path:

``` json
  "scripts": {
    "css": "node_modules/.bin/rncss -i style.css -o style.js",
    "start": "npm run css && node_modules/react-native/packager/packager.sh"
  }
```
----

notice `rncss`!

node_modules/.bin/rncss -i SOURCE_CSS_PATH_AND_FILE_NAME.css -o PATH_TO_AND_JS_FILENAME.js

what css script will do is, take an input (`-i`) css file and out (`-o') javascript file name, it will generate the follow:

``` javascript
module.exports = require('react-native').StyleSheet.create({"description":{"marginBottom":20,"fontSize":18,"textAlign":"center","color":"#656656"},"container":{"padding":30,"marginTop":65,"alignItems":"center"}});
```

then within `index.ios.js' just require in the generated `style.js`:

``` javascript
var styles = require('./style')
```

full example of the demo app:

``` javascript
'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} = React;

var styles = require('./style')

var saybrrlinksapps = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+Control+Z for dev menu
        </Text>
      </View>
    );
  }
});


AppRegistry.registerComponent('saybrrlinksapps', () => saybrrlinksapps);

```

**Comment by sabeurthabti** [comment]
@pukhalski a new version with file watching has been added, ignore the text above. 
`react-native-css@1.1.2` improves the cli
