### ISSUE TITLE
Repo description is misleading

### ISSUE THREAD

**Issue by ExplodingCabbage** [sabeurthabti/react-native-css#18]
To someone new to React Native and unfamiliar with styling in it, the description of this repo makes it sound like it will allow you to write components with `id` and `class` attributes and style them with CSS like you would style HTML elements in a browser. I had hoped to use this to reuse our CSS when converting an existing React application to React Native.

The reality is that it just creates a React Native Stylesheet object mapping CSS selectors to rules; it's still necessary to explicitly look up rule sets by selector to use them, rendering this tool useless for my use case, and only helpful for a very niche set of scenarios. This could be clearer in the repo description.

Perhaps remove the sentences *"Style React-Native components with css and built in support for SASS"* and *"Write your React-Native component styles in CSS/SCSS"* from the description and instead put something like "Generate a React Native Stylesheet from your CSS with the selectors as keys." That would be equally clear to people who understand React Native without confusing newbies.

**Comment by sabeurthabti** [comment]
@ExplodingCabbage you're right. Can you do a PR so you can get credit.

**Comment by ExplodingCabbage** [comment]
Will do tonight.

**Comment by sabeurthabti** [comment]
@ExplodingCabbage stilling waiting haha
