### ISSUE TITLE
bash: react-native-css: command not found

### ISSUE THREAD

**Issue by youngwind** [sabeurthabti/react-native-css#19]
I have a problem.
I install react-native-css through npm successfully，
<img width="289" alt="2015-12-27 10 48 00" src="https://cloud.githubusercontent.com/assets/8401872/12010682/ec42c540-aceb-11e5-9072-5a94c1cebcee.png">

but when I run "react-native-css" in terminal, it console a mistake as this.
```
bash: react-native-css: command not found
```
I can't figure it out.

**Comment by sabeurthabti** [comment]
@youngwind you will need to install it globally:

```bash
npm install -g react-native-css
```

**Comment by youngwind** [comment]
@sabeurthabti  it works!! thanks!
wheather it is because my react-native-cli was installed globally?
react-native-css need to be consistent ？

however，when i run this command 
```
react-native-css -i ./pages/index-style.scss -o ./pages/index-style.js --w
```
it can't watch my scss file's change and recompile automatically，i can't find the reason.
I have checked it many times.
<img width="910" alt="2015-12-27 11 20 31" src="https://cloud.githubusercontent.com/assets/8401872/12010808/765ad692-acf0-11e5-86b7-541bee3f80ee.png">

**Comment by sabeurthabti** [comment]
@youngwind I will investigate that.

**Comment by sabeurthabti** [comment]
@youngwind fixed in the latest version.
