### ISSUE TITLE
Unsupported properties should be ignored

### ISSUE THREAD

**Issue by caiosba** [sabeurthabti/react-native-css#22]
Right now if there is a property in the input CSS that is not supported by React Native, it will crash. It would be good to just ignore them.

**Comment by caiosba** [comment]
Created a pull request at #23

**Comment by sabeurthabti** [comment]
PR accepted, @caiosba when you get a chance can you add tests for that PR?

**Comment by caiosba** [comment]
Added tests and opened a new PR for that at #25

**Comment by sabeurthabti** [comment]
@caiosba awesome thank you.

**Comment by Zhouzi** [comment]
> Right now if there is a property in the input CSS that is not supported by React Native, it will crash.

Doesn't that mean you're using invalid CSS? If that's the case, it's probably better to be noticed early on or you'll end up with unknown bugs.

**Comment by jeffpearce** [comment]
Not necessarily.  You might be reusing css from a web project; RN supports only a subset of  CSS.
