### ISSUE TITLE
Question about default standard style rules in iOS

### ISSUE THREAD

**Issue by menway** [sabeurthabti/react-native-css#3]
Thanks for the package. Shall we include default standard style rules for iOS written in css (e.g. default colors, font sizes)? I think it'll be very helpful.

**Comment by sabeurthabti** [comment]
@menway can you explain it more? if you feel something should be added, please fork and I would be happy to accept pull requests. 

glad you like it, please tell me if you require more requires. I am thinking of making this use sass, so we can have variables etc.
