### ISSUE TITLE
npm WARN requires

### ISSUE THREAD

**Issue by fabiovella83** [sabeurthabti/react-native-css#30]
I get this message at the end of the npm install:

`npm WARN react-native-css@1.2.38 requires a peer of react-native@>=0.5 but none was installed.`

should I ignore it?

**Comment by alexmick** [comment]
No this means that `react-native` is required as a dependency but not installed automatically, you need to run `npm install react-native` manually to get it.
An explanation on why this is can be found [here](https://nodejs.org/en/blog/npm/peer-dependencies/)
