### ISSUE TITLE
react-native-css@1.2.39 requires a peer of react-native@>=0.5

### ISSUE THREAD

**Issue by minimaldesign** [sabeurthabti/react-native-css#31]
Running `npm install react-native-css --only=dev` I get this error:

`react-native-css@1.2.39 requires a peer of react-native@>=0.5`

Isn't the latest version of react-native 0.23?

Any pointer in the right direction much appreciated! :)

**Comment by sabeurthabti** [comment]
@minimaldesign Thanks for highlighting this. I will remove that check.

**Comment by sabeurthabti** [comment]
@minimaldesign https://circleci.com/gh/sabeurthabti/react-native-css/126 follow for the latest release.
