### ISSUE TITLE
Can i write LESS like CSS just like that in webpages with this tool?

### ISSUE THREAD

**Issue by mobilesite** [sabeurthabti/react-native-css#34]
Can i write LESS like CSS just like that in webpages with this tool? If not, is there any plan to support LESS. Thank you very much!

**Comment by sabeurthabti** [comment]
no plans to support less. I am willing to accept some sort of PR which allows LESS plugin.

**Comment by sabeurthabti** [comment]
@mobilesite closing since no PR submit and there has not been a drive for this.
