### ISSUE TITLE
Shorthands aren't properly expanding

### ISSUE THREAD

**Issue by jpomazal** [sabeurthabti/react-native-css#39]
Two value shorthands, e.g. `padding:10px 20px`, are expanding only into Top and Bottom using the Left, Right values, e.g. `{paddingTop:20, paddingBottom:20}`.

Additionally, border-width and border-radius are also shorthands however aren't treated as such, e.g. `border-width: 1px 0` is converted to `{borderWidth: 10}`.

**Comment by sabeurthabti** [comment]
thank you
