### ISSUE TITLE
Convert properties that don't match their CSS equivalent

### ISSUE THREAD

**Issue by stowball** [sabeurthabti/react-native-css#47]
For instance:
- text-decoration should be converted to textDecorationLine
- flex-grow to flex
- vertical-align to textAlignVertical
- `textAlignVertical: "middle"` to `textAlignVertical: "center"`
- transforms to an array, eg: `translate(100) scaleY(100)` to `[{ translate: 100, scaleY: 100 }]`
- `position: fixed` to `position: "absolute"`
- `border-(top|right|bottom|left): 0|none` to `border(Top|Right|Bottom|Left)Width: 0`

This would help to re-use existing CSS.

**Comment by sabeurthabti** [comment]
@stowball Hi,  Thank you for taking time to document this. As you're aware this is an open-source project. I wish I had the time to work on all these great suggestions, but I cannot right now. I would love to see you contribute these great suggestions. I can assist you in any way possible. Hit me up on messenger http://m.me/sabeur.thabti

**Comment by stowball** [comment]
Hopefully my employer will give the chance to help out on this

**Comment by sabeurthabti** [comment]
@stowball Understandable, if you company is benefiting from this module, it makes sense for them to contribute back. It only gets new features if people request and add them. I can make you contributor. 

What version are you using, I think you last bullet point is covered.

**Comment by stowball** [comment]
@sabeurthabti Yeah, we're currently just in the exploration/investigation phase of trying React Native, so this was the first thing I tried.

It's possible #5 is fixed, the rules may have originally had `!important` on them before, so they couldn't get converted to a Number.

That's another request, strip all `!important`s first before converting.

**Comment by sabeurthabti** [comment]
closing based on #52
