### ISSUE TITLE
I have write a gulp plugin for this  base your code

### ISSUE THREAD

**Issue by soliury** [sabeurthabti/react-native-css#5]
I write the [gulp-react-native-css](https://github.com/soliury/gulp-react-native-css) base your code, now with gulp, can get mutil input , and output to mutil dir.

**Comment by sabeurthabti** [comment]
@soliury +1 
awesome man. I will add it on the readme.

**Comment by sabeurthabti** [comment]
@soliury if you want to contribute code changes here please do.

**Comment by soliury** [comment]
OK, I will sent your a PR then.

**Comment by soliury** [comment]
I have sent a PR, Please check.

**Comment by sabeurthabti** [comment]
will do :+1:  @soliury

**Comment by sabeurthabti** [comment]
@soliury version 1.1.5 has your code base, it has been release. awesome job man. I will do further cleaning up and add better tests on the weekend.

**Comment by soliury** [comment]
ok. I am considering to add more functional to this project , such as border.

**Comment by sabeurthabti** [comment]
@soliury go for it :)
