### ISSUE TITLE
undefined is not a function (Symbol.iterator)

### ISSUE THREAD

**Issue by anzorb** [sabeurthabti/react-native-css#60]
react-native@0.47.2
react-native-css@2.0.7
Android 7.1.1
Only happens when remote debugging is turned off.
Crapping out on line 95 of build/index

```
 for (var _iterator = stylesheet.rules[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {

```
This line was transpiled from src/index at line 65:
```
 65 for (const rule of stylesheet.rules) {
```

Looks like the guys at styled components faced the same issue and removed dependency on (for of) https://github.com/styled-components/css-to-react-native/issues/31

![screenshot_20170905-210413](https://user-images.githubusercontent.com/1194338/30089949-32867b18-927e-11e7-83ca-943b6853875d.png)

**Comment by sabeurthabti** [comment]
@anzorb I'd love a PR from yourself on this. I will try to have a look at fixing this issue, however, I am traveling until tomorrow. 

We shouldn't be using Symbol.

**Comment by sabeurthabti** [comment]
@anzorb please try ` react-native-css@2.1.2`this should be fixed.

https://github.com/sabeurthabti/react-native-css/commit/d52ac846673c6cb515cd16822cee279f032e9ce6#diff-dfbff627e6c248bcb3b61d7d06da9ca9R105
