### ISSUE TITLE
scss - font-weight value needs double quotes

### ISSUE THREAD

**Issue by ngduc** [sabeurthabti/react-native-css#9]
Hi, I got an issue:
My SCSS:
txt {
	color: #00f;
	font-weight: 400;
}
is translated to JS:
module.exports = require('react-native').StyleSheet.create({
    "txt": {
        "color": "#00f",
        "fontWeight": 400
    }
});
but React Native throws an error that 400 has to be within double quotes like "400"

**Comment by sabeurthabti** [comment]
will investigate

**Comment by dorthwein** [comment]
+1 running into the same issue here

**Comment by sabeurthabti** [comment]
I am happy to accept pull requests @dorthwein @ngduc. I will be free to look at this evening.

**Comment by sabeurthabti** [comment]
just to update you guys, this is an issue with the library we are using underneath to convert css to json. I will see whats the best solution.

**Comment by sabeurthabti** [comment]
I am doing a release soon.

**Comment by sabeurthabti** [comment]
@ngduc @dorthwein 

```
1.1.6
```
please use this version.

**Comment by davidgruebl** [comment]
fixed: https://github.com/davidgruebl/react-native-css/commit/2ff193f230019590b19e4772d7149fe549bf22fd
